image: alpine

pages:
  script:
  - apk --no-cache add gcc make linux-headers musl-dev
  - apk --no-cache add py2-pip python-dev graphviz 
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-plantuml
  - pip install ipython
  - wget https://sourceforge.net/projects/plantuml/files/latest/download -O /plantuml.jar
#  - apk add --update --no-cache graphviz ttf-freefont openjdk7
#  - apk update && apk upgrade && apk add --no-cache bash git openssh
#  - sudo apt-get install graphviz openjdk-7-jdk git-core maven
#  - git clone https://github.com/plantuml/plantuml-server.git
#  - cd plantuml-server
#  - mvn package
  - cd doc
  - make html
  - cd ..
  - mkdir public/
  - cp -r doc/build/html/* public/
  artifacts:
    paths:
    - public
  only:
  - refguide 
