stages:
    - pages
    - testing

testing:
    image: git.jinr.ru:5005/gna/gna/root-minimal:latest
    stage: testing
    
    script:
    - ls && pwd
    - source /soft/root-6.18.04/build/bin/thisroot.sh
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . -- -j$(nproc --all)
    - cd ..
    - export LD_LIBRARY_PATH=$PWD/build:$LD_LIBRARY_PATH && export PYTHONPATH=$PWD/pylib:$PYTHONPATH
    - pytest
    only:
    - master

pages:
    image: alpine
    stage: pages
   
    script:
    - apk --no-cache add gcc make linux-headers musl-dev
    - apk --no-cache add py2-pip python-dev graphviz openjdk7 fontconfig ttf-dejavu
    - apk --no-cache add openssl doxygen
    - pip install sphinx
    - pip install sphinx_rtd_theme
    - pip install sphinxcontrib-plantuml
    - pip install ipython
    - cd doc
    - make html
    - make doxygen
    - cd ..
    - mkdir public/
    - mkdir -p public/doxygen
    - cp -r doc/build/html/* public/
    - cp -r doc/doxygen/html/* public/doxygen/
    artifacts:
      paths:
      - public
    only:
    - master 
