image: alpine

pages:
  script:
  - apk --no-cache add py2-pip python-dev py2-ipython
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-plantuml
  - apk --no-cache add make
  - cd doc
  - make html
  artifacts:
    paths:
    - doc/build/html
  only:
  - master 
