image: alpine

pages:
  script:
  - apk --no-cache add gcc make linux-headers musl-dev
  - apk --no-cache add py2-pip python-dev graphviz openjdk7 fontconfig ttf-dejavu
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-plantuml
  - pip install ipython
  - apk update && apk add ca-certificates wget && update-ca-certificates
  - apk --no-cache add openssl doxygen
  - wget https://downloads.sourceforge.net/project/plantuml/plantuml.jar -O /plantuml.jar
  - java -jar /plantuml.jar -testdot 
  - cd doc
  - make html
  - make doxygen
  - cd ..
  - mkdir public/
  - mkdir -p public/doxygen
  - cp -r doc/build/html/* public/
  - cp -r doc/doxygen/html/* public/doxygen/
  artifacts:
    paths:
    - public
  only:
  - master 
