image: alpine

pages:
  script:
  - apk --no-cache add gcc make linux-headers musl-dev
  - apk --no-cache add py2-pip python-dev graphviz openjdk7 fontconfig ttf-dejavu
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-plantuml
  - pip install ipython
  - apk update && apk add ca-certificates wget && update-ca-certificates
  - apk --no-cache add openssl
  - wget https://sourceforge.net/projects/plantuml/files/latest/download -O /plantuml.jar
  - java -jar /plantuml.jar -testdot 
  - cd doc
  - make html
  - cd ..
  - mkdir public/
  - cp -r doc/build/html/* public/
  artifacts:
    paths:
    - public
  only:
  - master 
