#!/bin/env python2

import ROOT
import sys
from gna import dispatch
from gna import bindings

if __name__ == "__main__":
    argv = sys.argv
    sys.argv = [argv[0]]

    import load

    sys.argv = argv

    bindings.setup(ROOT)
    dispatch.run()
